# https://taskfile.dev

version: '3'

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

vars:
  BUILD_MESSAGE: Building Docker Image - Version $VERSION
  RUN_MESSAGE: Running Docker Container - Version $VERSION
  RUN_PROJECT_MESSAGE: Running Project - Version $VERSION
  CLEAR_MESSAGE: Clearing Docker Container - Version $VERSION
  TEST_MESSAGE: Testing Service - Version $VERSION

tasks:
  build:
    cmds:
      - echo "{{.BUILD_MESSAGE}}"
      - chmod +x ./container_build.sh
      - bash ./container_build.sh $VERSION
    silent: true
  run:
    cmds:
      - echo "{{.RUN_MESSAGE}}"
      - podman run -d --name worsty -p 5000:5000 worst/worst-note:$VERSION
    silent: true
  clear:
    cmds:
      - echo "{{.CLEAR_MESSAGE}}"
      - podman kill worsty
      - podman rm worsty   
    silent: true
  test:
    cmds:
      - echo "{{.CLEAR_MESSAGE}}"
      - chmod +x ./test.sh
      - bash ./test.sh
      - echo $?
    silent: true
  run_project:
    cmds:
      - echo "{{.RUN_PROJECT_MESSAGE}}"
      - python ./main.py
    silent: true
